version: '3.3'
services:
  crescent:
    build: crescent
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ${PWD}/crescent/config:/usr/local/src/Crescent/config
    tty: true
  db:
    build: db
    hostname: 'db'
    ports:
      - "3060:3060"
    environment:
      POSTGRES_USER: crescent
      POSTGRES_PASSWORD: cres
      PGPORT: 5432
    volumes:
      - ${PWD}/db/data:/var/lib/postgresql/data
  web:
    build: web
    ports:
      - "81:80"
    depends_on:
      - crescent
